# Generated by Django 4.2.15 on 2025-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('date_enrollled', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
